using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Cors;
using AIWorkoutNow.Api.Services;
using AIWorkoutNow.Api.Models;

namespace AIWorkoutNow.Api.Controllers;

[ApiController]
[Route("")]
[EnableCors("AllowAll")]
public class PricingController : ControllerBase
{
    private readonly IDynamoDBService _dynamoService;

    public PricingController(IDynamoDBService dynamoService)
    {
        _dynamoService = dynamoService;
    }

    [HttpGet("pricing-plans")]
    public async Task<IActionResult> GetPricingPlans()
    {
        try
        {
            var plans = await _dynamoService.GetAllPricingPlansAsync();
            return Ok(plans);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new { message = "Failed to get pricing plans", error = ex.Message });
        }
    }

    [HttpGet("free-workouts-remaining")]
    public async Task<IActionResult> GetFreeWorkoutsRemaining([FromQuery] string deviceId)
    {
        try
        {
            // Count total workouts generated by this device
            // For free tier, we track total workouts (not daily)
            var totalWorkouts = await _dynamoService.GetTotalFreeWorkoutsAsync(deviceId);
            var remaining = Math.Max(0, 3 - totalWorkouts);
            
            return Ok(new { remaining = remaining, totalUsed = totalWorkouts });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new { message = "Failed to get free workouts", error = ex.Message });
        }
    }

    [HttpGet("user-access-status")]
    public async Task<IActionResult> GetUserAccessStatus([FromQuery] string deviceId)
    {
        try
        {
            // Check free workouts
            var totalWorkouts = await _dynamoService.GetTotalFreeWorkoutsAsync(deviceId);
            var freeWorkoutsRemaining = Math.Max(0, 3 - totalWorkouts);
            var hasFreeAccess = freeWorkoutsRemaining > 0;

            // Check unlimited access
            var unlimitedPurchase = await _dynamoService.GetActiveUnlimitedPurchaseAsync(deviceId);
            var hasUnlimitedAccess = unlimitedPurchase != null;

            // Check token balance
            var tokens = await _dynamoService.GetUserTokensAsync(deviceId);
            var hasTokenAccess = tokens != null && tokens.TokensRemaining > 0;

            return Ok(new
            {
                hasFreeAccess,
                freeWorkoutsRemaining,
                hasUnlimitedAccess,
                unlimitedExpiresAt = unlimitedPurchase?.ExpiresAt,
                hasTokenAccess,
                tokensRemaining = tokens?.TokensRemaining ?? 0,
                canGenerateWorkout = hasFreeAccess || hasUnlimitedAccess || hasTokenAccess
            });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new { message = "Failed to get access status", error = ex.Message });
        }
    }
}
