using Microsoft.AspNetCore.Mvc;
using AIWorkoutNow.Api.Services;
using AIWorkoutNow.Api.Models;

namespace AIWorkoutNow.Api.Controllers;

[ApiController]
[Route("")]
public class PricingController : ControllerBase
{
    private readonly IDynamoDBService _dynamoService;
    private static List<PricingPlan>? _cachedPlans;
    private static DateTime _cacheExpiry = DateTime.MinValue;
    private static readonly object _cacheLock = new object();
    private static readonly TimeSpan CacheDuration = TimeSpan.FromMinutes(5); // Cache for 5 minutes
    
    // Note: Static constructor removed - we'll populate cache on first request
    // This avoids dependency injection issues in static constructor

    public PricingController(IDynamoDBService dynamoService)
    {
        _dynamoService = dynamoService;
    }

    public static void InvalidateCache()
    {
        lock (_cacheLock)
        {
            _cachedPlans = null;
            _cacheExpiry = DateTime.MinValue;
            Console.WriteLine("[PricingController] Cache invalidated");
        }
    }

    [HttpGet("pricing-plans")]
    public async Task<IActionResult> GetPricingPlans()
    {
        var startTime = DateTime.UtcNow;
        try
        {
            List<PricingPlan> plans;
            
            // Check cache
            lock (_cacheLock)
            {
                if (_cachedPlans != null && DateTime.UtcNow < _cacheExpiry)
                {
                    var cacheTime = (DateTime.UtcNow - startTime).TotalMilliseconds;
                    Console.WriteLine($"[PricingController] Returning cached pricing plans ({cacheTime:F2}ms)");
                    plans = _cachedPlans;
                }
                else
                {
                    plans = null!; // Will fetch from DB
                }
            }
            
            // Fetch from service if cache expired or empty
            // This will be fast due to table existence caching in DynamoDBService
            if (plans == null)
            {
                Console.WriteLine("[PricingController] Cache miss, fetching from service (will be fast due to table existence cache)");
                var fetchStart = DateTime.UtcNow;
                plans = await _dynamoService.GetAllPricingPlansAsync();
                var fetchTime = (DateTime.UtcNow - fetchStart).TotalMilliseconds;
                Console.WriteLine($"[PricingController] Fetched {plans.Count} plans in {fetchTime:F2}ms");
                
                // Always update cache, even if it's defaults (to avoid repeated calls)
                lock (_cacheLock)
                {
                    _cachedPlans = plans;
                    _cacheExpiry = DateTime.UtcNow.Add(CacheDuration);
                    Console.WriteLine($"[PricingController] Cached pricing plans, expires at {_cacheExpiry}");
                }
            }

            // Set cache headers for browser caching
            Response.Headers["Cache-Control"] = "public, max-age=300"; // 5 minutes
            Response.Headers["ETag"] = $"\"{plans.GetHashCode()}\"";
            
            var totalTime = (DateTime.UtcNow - startTime).TotalMilliseconds;
            Console.WriteLine($"[PricingController] Total response time: {totalTime:F2}ms");
            
            return Ok(plans);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[PricingController] Error in GetPricingPlans: {ex.Message}");
            Console.WriteLine($"[PricingController] Stack trace: {ex.StackTrace}");
            return StatusCode(500, new { message = "Failed to get pricing plans", error = ex.Message });
        }
    }

    [HttpGet("free-workouts-remaining")]
    public async Task<IActionResult> GetFreeWorkoutsRemaining([FromQuery] string deviceId)
    {
        try
        {
            // Count total workouts generated by this device
            // For free tier, we track total workouts (not daily)
            var totalWorkouts = await _dynamoService.GetTotalFreeWorkoutsAsync(deviceId);
            var remaining = Math.Max(0, 3 - totalWorkouts);
            
            return Ok(new { remaining = remaining, totalUsed = totalWorkouts });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new { message = "Failed to get free workouts", error = ex.Message });
        }
    }

    [HttpGet("user-access-status")]
    public async Task<IActionResult> GetUserAccessStatus([FromQuery] string deviceId)
    {
        try
        {
            // Check free workouts
            var totalWorkouts = await _dynamoService.GetTotalFreeWorkoutsAsync(deviceId);
            var freeWorkoutsRemaining = Math.Max(0, 3 - totalWorkouts);
            var hasFreeAccess = freeWorkoutsRemaining > 0;

            // Check unlimited access
            var unlimitedPurchase = await _dynamoService.GetActiveUnlimitedPurchaseAsync(deviceId);
            var hasUnlimitedAccess = unlimitedPurchase != null;

            // Check token balance
            var tokens = await _dynamoService.GetUserTokensAsync(deviceId);
            var hasTokenAccess = tokens != null && tokens.TokensRemaining > 0;

            return Ok(new
            {
                hasFreeAccess,
                freeWorkoutsRemaining,
                hasUnlimitedAccess,
                unlimitedExpiresAt = unlimitedPurchase?.ExpiresAt?.ToString("O"),
                hasTokenAccess,
                tokensRemaining = tokens?.TokensRemaining ?? 0,
                canGenerateWorkout = hasFreeAccess || hasUnlimitedAccess || hasTokenAccess
            });
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[PricingController] Error in GetUserAccessStatus: {ex.Message}");
            Console.WriteLine($"[PricingController] Stack trace: {ex.StackTrace}");
            return StatusCode(500, new { message = "Failed to get access status", error = ex.Message });
        }
    }
}
