using Microsoft.AspNetCore.Mvc;
using AIWorkoutNow.Api.Services;
using AIWorkoutNow.Api.Models;

namespace AIWorkoutNow.Api.Controllers;

[ApiController]
[Route("")]
public class PricingController : ControllerBase
{
    private readonly IDynamoDBService _dynamoService;
    private readonly IConfigService _configService;
    private static List<PricingPlan>? _cachedPlans;
    private static DateTime _cacheExpiry = DateTime.MinValue;
    private static readonly object _cacheLock = new object();
    private static readonly TimeSpan CacheDuration = TimeSpan.FromMinutes(5); // Cache for 5 minutes
    
    // Note: Static constructor removed - we'll populate cache on first request
    // This avoids dependency injection issues in static constructor

    public PricingController(IDynamoDBService dynamoService, IConfigService configService)
    {
        _dynamoService = dynamoService;
    }

    public static void InvalidateCache()
    {
        lock (_cacheLock)
        {
            _cachedPlans = null;
            _cacheExpiry = DateTime.MinValue;
            Console.WriteLine("[PricingController] Cache invalidated");
        }
    }

    [HttpGet("pricing-plans")]
    public async Task<IActionResult> GetPricingPlans()
    {
        var startTime = DateTime.UtcNow;
        try
        {
            List<PricingPlan> plans;
            
            // Check cache
            lock (_cacheLock)
            {
                if (_cachedPlans != null && DateTime.UtcNow < _cacheExpiry)
                {
                    var cacheTime = (DateTime.UtcNow - startTime).TotalMilliseconds;
                    Console.WriteLine($"[PricingController] Returning cached pricing plans ({cacheTime:F2}ms)");
                    plans = _cachedPlans;
                }
                else
                {
                    plans = null!; // Will fetch from DB
                }
            }
            
            // Fetch from service if cache expired or empty
            // This will be fast due to table existence caching in DynamoDBService
            if (plans == null)
            {
                Console.WriteLine("[PricingController] Cache miss, fetching from service (will be fast due to table existence cache)");
                var fetchStart = DateTime.UtcNow;
                plans = await _dynamoService.GetAllPricingPlansAsync();
                var fetchTime = (DateTime.UtcNow - fetchStart).TotalMilliseconds;
                Console.WriteLine($"[PricingController] Fetched {plans.Count} plans in {fetchTime:F2}ms");
                
                // Always update cache, even if it's defaults (to avoid repeated calls)
                lock (_cacheLock)
                {
                    _cachedPlans = plans;
                    _cacheExpiry = DateTime.UtcNow.Add(CacheDuration);
                    Console.WriteLine($"[PricingController] Cached pricing plans, expires at {_cacheExpiry}");
                }
            }

            // Set cache headers for browser caching
            Response.Headers["Cache-Control"] = "public, max-age=300"; // 5 minutes
            Response.Headers["ETag"] = $"\"{plans.GetHashCode()}\"";
            
            var totalTime = (DateTime.UtcNow - startTime).TotalMilliseconds;
            Console.WriteLine($"[PricingController] Total response time: {totalTime:F2}ms");
            
            return Ok(plans);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[PricingController] Error in GetPricingPlans: {ex.Message}");
            Console.WriteLine($"[PricingController] Stack trace: {ex.StackTrace}");
            return StatusCode(500, new { message = "Failed to get pricing plans", error = ex.Message });
        }
    }

    [HttpGet("free-workouts-remaining")]
    public async Task<IActionResult> GetFreeWorkoutsRemaining([FromQuery] string deviceId)
    {
        try
        {
            // Count total workouts generated by this device
            // For free tier, we track total workouts (not daily)
            var totalWorkouts = await _dynamoService.GetTotalFreeWorkoutsAsync(deviceId);
            var remaining = Math.Max(0, 3 - totalWorkouts);
            
            return Ok(new { remaining = remaining, totalUsed = totalWorkouts });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new { message = "Failed to get free workouts", error = ex.Message });
        }
    }

    [HttpGet("user-access-status")]
    public async Task<IActionResult> GetUserAccessStatus([FromQuery] string deviceId)
    {
        try
        {
            // Check free workouts
            var totalWorkouts = await _dynamoService.GetTotalFreeWorkoutsAsync(deviceId);
            var freeWorkoutsRemaining = Math.Max(0, 3 - totalWorkouts);
            var hasFreeAccess = freeWorkoutsRemaining > 0;

            // Check token balance first (to detect unlimited via 999999 tokens)
            var tokens = await _dynamoService.GetUserTokensAsync(deviceId);
            var tokensRemaining = tokens?.TokensRemaining ?? 0;
            
            Console.WriteLine($"[PricingController] GetUserAccessStatus - DeviceId: {deviceId}, TokensRemaining: {tokensRemaining}, HasTokens: {tokens != null}");
            if (tokens != null && tokens.ExpiresAt.HasValue)
            {
                Console.WriteLine($"[PricingController] Token expires at: {tokens.ExpiresAt}");
            }
            
            // AGGRESSIVE FIX: If tokens are low (< 999999), check Stripe for completed payments
            if (tokensRemaining < 999999)
            {
                Console.WriteLine($"[PricingController] Tokens are low ({tokensRemaining}), checking Stripe for completed unlimited purchases...");
                try
                {
                    var stripeSecretKey = await _configService.GetStripeSecretKeyAsync();
                    
                    if (!string.IsNullOrEmpty(stripeSecretKey))
                    {
                        // Check recent Stripe sessions for this device
                        using var httpClient = new HttpClient();
                        httpClient.DefaultRequestHeaders.Authorization = 
                            new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", stripeSecretKey);
                        
                        // List recent checkout sessions (last 10)
                        var sessionsUrl = "https://api.stripe.com/v1/checkout/sessions?limit=10";
                        var sessionsResponse = await httpClient.GetAsync(sessionsUrl);
                        
                        if (sessionsResponse.IsSuccessStatusCode)
                        {
                            var sessionsContent = await sessionsResponse.Content.ReadAsStringAsync();
                            var sessionsData = System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, object>>(sessionsContent);
                            
                            if (sessionsData != null && sessionsData.ContainsKey("data"))
                            {
                                var sessionsList = sessionsData["data"] as System.Text.Json.JsonElement[];
                                if (sessionsList != null)
                                {
                                    foreach (var session in sessionsList)
                                    {
                                        try
                                        {
                                            var metadata = session.GetProperty("metadata");
                                            var deviceIdFromSession = metadata.GetProperty("deviceId").GetString();
                                            var planId = metadata.GetProperty("planId").GetString();
                                            var paymentStatus = session.GetProperty("payment_status").GetString();
                                            var sessionId = session.GetProperty("id").GetString();
                                            
                                            if (deviceIdFromSession == deviceId && paymentStatus == "paid")
                                            {
                                                Console.WriteLine($"[PricingController] Found paid session {sessionId} for device {deviceId}, plan: {planId}");
                                                
                                                // Check if this is an unlimited plan
                                                var plan = await _dynamoService.GetPricingPlanAsync(planId ?? "");
                                                if (plan != null && plan.IsUnlimited)
                                                {
                                                    Console.WriteLine($"[PricingController] AGGRESSIVE FIX: Granting unlimited access from Stripe check!");
                                                    
                                                    // Grant unlimited access immediately
                                                    if (tokens == null)
                                                    {
                                                        tokens = new UserTokens
                                                        {
                                                            DeviceId = deviceId,
                                                            TokensRemaining = 999999,
                                                            ExpiresAt = plan.UnlimitedDays.HasValue ? DateTime.UtcNow.AddDays(plan.UnlimitedDays.Value) : null
                                                        };
                                                    }
                                                    else
                                                    {
                                                        tokens.TokensRemaining = 999999;
                                                        if (plan.UnlimitedDays.HasValue)
                                                        {
                                                            tokens.ExpiresAt = DateTime.UtcNow.AddDays(plan.UnlimitedDays.Value);
                                                        }
                                                    }
                                                    
                                                    await _dynamoService.SaveUserTokensAsync(tokens);
                                                    tokensRemaining = 999999;
                                                    Console.WriteLine($"[PricingController] Successfully granted unlimited access via aggressive fix");
                                                    
                                                    // Break after first match
                                                    break;
                                                }
                                            }
                                        }
                                        catch (Exception ex)
                                        {
                                            Console.WriteLine($"[PricingController] Error processing Stripe session: {ex.Message}");
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"[PricingController] Error checking Stripe (non-critical): {ex.Message}");
                }
            }
            
            // Check if tokens indicate unlimited access (999999 is our marker for unlimited)
            var hasUnlimitedFromTokens = tokensRemaining >= 999999;
            
            // Check unlimited access from purchases table
            var unlimitedPurchase = await _dynamoService.GetActiveUnlimitedPurchaseAsync(deviceId);
            var hasUnlimitedFromPurchase = unlimitedPurchase != null;
            
            Console.WriteLine($"[PricingController] Unlimited check - FromTokens: {hasUnlimitedFromTokens}, FromPurchase: {hasUnlimitedFromPurchase}");
            if (unlimitedPurchase != null)
            {
                Console.WriteLine($"[PricingController] Unlimited purchase found - PlanId: {unlimitedPurchase.PlanId}, ExpiresAt: {unlimitedPurchase.ExpiresAt}");
            }
            
            // User has unlimited if either check passes
            var hasUnlimitedAccess = hasUnlimitedFromTokens || hasUnlimitedFromPurchase;
            
            // Use expiration from purchase if available, otherwise from tokens
            var unlimitedExpiresAt = unlimitedPurchase?.ExpiresAt ?? tokens?.ExpiresAt;
            
            var hasTokenAccess = tokens != null && tokensRemaining > 0 && !hasUnlimitedAccess;

            Console.WriteLine($"[PricingController] Final status - HasUnlimited: {hasUnlimitedAccess}, TokensRemaining: {tokensRemaining}, HasTokenAccess: {hasTokenAccess}");

            return Ok(new
            {
                hasFreeAccess,
                freeWorkoutsRemaining,
                hasUnlimitedAccess,
                unlimitedExpiresAt = unlimitedExpiresAt?.ToString("O"),
                hasTokenAccess,
                tokensRemaining = hasUnlimitedAccess ? 999999 : tokensRemaining, // Show 999999 for unlimited
                canGenerateWorkout = hasFreeAccess || hasUnlimitedAccess || hasTokenAccess
            });
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[PricingController] Error in GetUserAccessStatus: {ex.Message}");
            Console.WriteLine($"[PricingController] Stack trace: {ex.StackTrace}");
            return StatusCode(500, new { message = "Failed to get access status", error = ex.Message });
        }
    }
}
