using AIWorkoutNow.Api.Models;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.Model;

namespace AIWorkoutNow.Api.Services;

public class AmazonAffiliateService : IAmazonAffiliateService
{
    private readonly IAmazonDynamoDB _dynamoDB;
    private readonly IConfigService _configService;
    private readonly string _affiliateClicksTable;
    private readonly string _region;
    private string? _cachedAssociateId;

    public AmazonAffiliateService(IAmazonDynamoDB dynamoDB, IConfigService configService)
    {
        _dynamoDB = dynamoDB;
        _configService = configService;
        _region = Environment.GetEnvironmentVariable("AWS_REGION") ?? "us-east-1";
        var tablePrefix = Environment.GetEnvironmentVariable("TABLE_PREFIX") ?? "AIWorkoutNow";
        _affiliateClicksTable = $"{tablePrefix}-AffiliateClicks";
    }

    private string GetAssociateId()
    {
        if (_cachedAssociateId != null) return _cachedAssociateId;
        var tag = _configService.GetAmazonAssociateIdAsync().Result;
        _cachedAssociateId = !string.IsNullOrEmpty(tag) ? tag : "aiworkoutnow-20";
        return _cachedAssociateId;
    }

    public string GenerateAffiliateLink(string asin, string? linkText = null)
    {
        // For ASIN-based links (if ASIN is provided)
        if (!string.IsNullOrEmpty(asin) && asin.StartsWith("B", StringComparison.OrdinalIgnoreCase))
        {
            var baseUrl = "https://www.amazon.com";
            var link = $"{baseUrl}/dp/{asin}?tag={GetAssociateId()}";
            
            if (!string.IsNullOrEmpty(linkText))
            {
                link += $"&linkCode=ll1&linkId={linkText}";
            }
            
            return link;
        }
        
        // For search-based links (using keywords)
        return GenerateSearchAffiliateLink(asin, linkText);
    }

    private string GenerateSearchAffiliateLink(string searchKeywords, string? linkText = null)
    {
        // Amazon Associates search link format
        // Format: https://www.amazon.com/s?k={keywords}&tag={ASSOCIATE_ID}
        var baseUrl = "https://www.amazon.com";
        var encodedKeywords = Uri.EscapeDataString(searchKeywords);
        var link = $"{baseUrl}/s?k={encodedKeywords}&tag={GetAssociateId()}";
        
        if (!string.IsNullOrEmpty(linkText))
        {
            link += $"&linkCode=ll2&linkId={linkText}";
        }
        
        return link;
    }

    public async Task<List<ProductRecommendation>> GetProductRecommendationsAsync(
        string workoutType, 
        string equipment, 
        List<string> exercises)
    {
        // Product recommendations are now generated by OpenAI and passed in via the workout
        // This method is kept for backward compatibility but should receive recommendations from the workout
        // The actual recommendations come from OpenAI in the workout response
        return new List<ProductRecommendation>();
    }

    public List<ProductRecommendation> ProcessProductRecommendations(List<ProductRecommendation>? recommendations, string workoutType)
    {
        if (recommendations == null || recommendations.Count == 0)
        {
            return new List<ProductRecommendation>();
        }

        // Generate affiliate links for each recommendation using search keywords
        foreach (var product in recommendations)
        {
            // Use searchKeywords if available, otherwise use category or title
            var searchTerms = !string.IsNullOrEmpty(product.SearchKeywords) 
                ? product.SearchKeywords 
                : (!string.IsNullOrEmpty(product.Category) ? product.Category : product.Title);
            
            // Generate affiliate link using search terms
            product.AffiliateLink = GenerateSearchAffiliateLink(
                searchTerms, 
                $"{workoutType}-{product.Category}"
            );
            
            // Set ASIN to search keywords for tracking purposes (we'll track by keywords)
            if (string.IsNullOrEmpty(product.ASIN))
            {
                product.ASIN = searchTerms; // Use keywords as identifier for tracking
            }
        }

        return recommendations;
    }

    public async Task TrackAffiliateClickAsync(string deviceId, string asin, string workoutId, string? linkText = null)
    {
        try
        {
            var click = new Dictionary<string, AttributeValue>
            {
                ["ClickId"] = new AttributeValue { S = Guid.NewGuid().ToString() },
                ["DeviceId"] = new AttributeValue { S = deviceId },
                ["ASIN"] = new AttributeValue { S = asin },
                ["WorkoutId"] = new AttributeValue { S = workoutId },
                ["Timestamp"] = new AttributeValue { S = DateTime.UtcNow.ToString("O") },
                ["LinkText"] = new AttributeValue { S = linkText ?? "unknown" },
                ["Region"] = new AttributeValue { S = _region }
            };

            await _dynamoDB.PutItemAsync(new PutItemRequest
            {
                TableName = _affiliateClicksTable,
                Item = click
            });
        }
        catch (Exception ex)
        {
            // Log error but don't fail the request
            Console.WriteLine($"Error tracking affiliate click: {ex.Message}");
        }
    }
}
